export const SET_PERSON = 'SET_PERSON';
export const SET_PERSON_ID = 'SET_PERSON_ID';
export const SET_CARDLIST = 'SET_CARDLIST';
export const SET_PERMA_CARDLIST = 'SET_PERMA_CARDLIST';
export const SET_FILTER_CARDLIST = 'SET_FILTER_CARDLIST';
export const SET_COUNTER = 'SET_COUNTER';
